### ISSUE TITLE
Vipnode v2.0 host with Parity v2.4.6 broken compatibility for Vipnode v2.0 Pool (dappnode)

### ISSUE THREAD

**Issue by Beasta** [vipnode/vipnode#33] opened 2019-06-08 00:39 UTC
2019-06-08 00:36:16.986 WARNING This is a pre-release version (dev). It can stop working at any time.
2019-06-08 00:36:16.987 INFO Connecting to Ethereum node: http://my.ethchain.dnp.dappnode.eth:8545
2019-06-08 00:36:17.409 INFO Connected to vipnode pool: wss://pool.vipnode.org/
[host] 2019/06/08 00:36:17 Connected to local node: enode://8b4a82e9896ce01f697847237aab6552b25249064e837781577e1302c89cf6159ff9102e42b81e9143391add54da7b550f8ef606xdc2c9182aa9aabf260f6dcac@172.33.1.6:30303
[host] 2019/06/08 00:36:17 Registered on pool: Version vipnode/pool/v2.0
host failed: json: cannot unmarshal object into Go struct field PeerInfo.name of type string
 -> Error type *json.UnmarshalTypeError is missing an explanation. Please open an issue at https://github.com/vipnode/vipnode

**Comment by shazow** [comment] 2019-06-08 01:46
Ah, looks like DAppNode is using the master branch which is breaking compatibility with the current running pool, rather than the latest tagged release. I'll reach out, or deploy a new pool next week.

**Comment by eduadiez** [comment] 2019-06-08 07:19
Hi! We use v2.0 release to build our image: 
https://github.com/dappnode/DAppNodePackage-vipnode/blob/947f5f9ec2ec2ef10c1caff39b306d3aa7fda59d/build/Dockerfile#L3

Everything worked perfectly until we updated parity to version v2.4.6, with previous versions this error didn't happen.

About our parity, we run it with this parameters:
```
parity --jsonrpc-port 8545 --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-cors all --ws-interface 0.0.0.0 --ws-port 8546 --ws-origins all --ws-hosts all --ws-max-connections 1000
```

Thanks for your help

**Comment by shazow** [comment] 2019-06-08 15:40
@eduadiez Ah good call. I couldn't tell the version because it wasn't injected like I normally do it:

https://github.com/shazow/ssh-chat/blob/master/Makefile#L6-L7

The params are helpful, I'll try it again. Thanks!

**Comment by shazow** [comment] 2019-06-10 20:47
Okay managed to reproduce it. Looks like Parity changed their output layout for `parity_netPeers`:
 https://github.com/paritytech/parity-ethereum/pull/10247

Working on a workaround.

**Comment by shazow** [comment] 2019-06-10 21:47
Reviews appreciated for #35, will merge it tomorrow and push out v2.0.1.

**Comment by shazow** [comment] 2019-06-11 13:18
Still need to backport and release v2.0.1, will close this issue when that's done.

**Comment by shazow** [comment] 2019-06-11 14:53
Tagged v2.0.1: https://github.com/vipnode/vipnode/releases/tag/v2.0.1

I'll be adding binaries shortly, but should be good to go. Please let me know if there are any problems! (cc @vdo)

**Closed by shazow** 2019-06-11 14:53 UTC
Labels: bug
